In [1]:
import pandas as pd

In [2]:
client = pd.read_csv(
    "../data/raw/client.asc",
    sep=";"
)

In [3]:
client.head()

   client_id  birth_number  district_id
0          1        706213           18
1          2        450204            1
2          3        406009            1
3          4        561201            5
4          5        605703            5

In [4]:
client.shape

(5369, 3)

In [5]:
client.columns

Index(['client_id', 'birth_number', 'district_id'], dtype='object')

In [6]:
client.dtypes

client_id       int64
birth_number    int64
district_id     int64
dtype: object

In [7]:
client.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5369 entries, 0 to 5368
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   client_id     5369 non-null   int64
 1   birth_number  5369 non-null   int64
 2   district_id   5369 non-null   int64
dtypes: int64(3)
memory usage: 126.0 KB

In [8]:
client["client_id"].nunique()

5369

In [9]:
client["client_id"].duplicated().sum()

np.int64(0)

In [10]:
client.isna().sum()

client_id       0
birth_number    0
district_id     0
dtype: int64

In [11]:
district = pd.read_csv(
    "../data/raw/district.asc",
    sep=";",
    header=None
)

In [12]:
district.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16
1,1,Hl.m. Praha,Prague,1204953,0,0,0,1,1,100.0,12541,0.29,0.43,167,85677,99107
2,2,Benesov,central Bohemia,88884,80,26,6,2,5,46.7,8507,1.67,1.85,132,2159,2674
3,3,Beroun,central Bohemia,75232,55,26,4,1,5,41.7,8980,1.95,2.21,111,2824,2813
4,4,Kladno,central Bohemia,149893,63,29,6,2,6,67.4,9753,4.64,5.05,109,5244,5892

In [13]:
district = pd.read_csv(
    "../data/raw/district.asc",
    sep=";"
)

district.head()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16
0,1,Hl.m. Praha,Prague,1204953,0,0,0,1,1,100.0,12541,0.29,0.43,167,85677,99107
1,2,Benesov,central Bohemia,88884,80,26,6,2,5,46.7,8507,1.67,1.85,132,2159,2674
2,3,Beroun,central Bohemia,75232,55,26,4,1,5,41.7,8980,1.95,2.21,111,2824,2813
3,4,Kladno,central Bohemia,149893,63,29,6,2,6,67.4,9753,4.64,5.05,109,5244,5892
4,5,Kolin,central Bohemia,95616,65,30,4,1,6,51.4,9307,3.85,4.43,118,2616,3040

In [14]:
district.shape

(77, 16)

In [15]:
district.dtypes

A1       int64
A2      object
A3      object
A4       int64
A5       int64
A6       int64
A7       int64
A8       int64
A9       int64
A10    float64
A11      int64
A12     object
A13    float64
A14      int64
A15     object
A16      int64
dtype: object

In [16]:
district.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A1      77 non-null     int64
 1   A2      77 non-null     object
 2   A3      77 non-null     object
 3   A4      77 non-null     int64
 4   A5      77 non-null     int64
 5   A6      77 non-null     int64
 6   A7      77 non-null     int64
 7   A8      77 non-null     int64
 8   A9      77 non-null     int64
 9   A10     77 non-null     float64
 10  A11     77 non-null     int64
 11  A12     77 non-null     object
 12  A13     77 non-null     float64
 13  A14     77 non-null     int64
 14  A15     77 non-null     object
 15  A16     77 non-null     int64
dtypes: float64(2), int64(10), object(4)
memory usage: 9.8+ KB

In [17]:
client["district_id"].nunique()

77

In [18]:
district["A1"].nunique()

77

In [19]:
client["district_id"].isin(district["A1"]).all()

np.True_

In [20]:
district.columns = [
    "district_id",
    "district_name",
    "region",
    "population",
    "municipalities_under_2000",
    "municipalities_2000_9999",
    "municipalities_10000_99999",
    "municipalities_over_100000",
    "number_of_cities",
    "urban_population_pct",
    "average_salary",
    "unemployment_rate_1995",
    "unemployment_rate_1996",
    "entrepreneurs_per_1000",
    "crimes_1995",
    "crimes_1996"
]

In [21]:
district.head()

,district_id,district_name,region,population,municipalities_under_2000,municipalities_2000_9999,municipalities_10000_99999,municipalities_over_100000,number_of_cities,urban_population_pct,average_salary,unemployment_rate_1995,unemployment_rate_1996,entrepreneurs_per_1000,crimes_1995,crimes_1996
0,1,Hl.m. Praha,Prague,1204953,0,0,0,1,1,100.0,12541,0.29,0.43,167,85677,99107
1,2,Benesov,central Bohemia,88884,80,26,6,2,5,46.7,8507,1.67,1.85,132,2159,2674
2,3,Beroun,central Bohemia,75232,55,26,4,1,5,41.7,8980,1.95,2.21,111,2824,2813
3,4,Kladno,central Bohemia,149893,63,29,6,2,6,67.4,9753,4.64,5.05,109,5244,5892
4,5,Kolin,central Bohemia,95616,65,30,4,1,6,51.4,9307,3.85,4.43,118,2616,3040

In [22]:
district.columns

Index(['district_id', 'district_name', 'region', 'population',
       'municipalities_under_2000', 'municipalities_2000_9999',
       'municipalities_10000_99999', 'municipalities_over_100000',
       'number_of_cities', 'urban_population_pct', 'average_salary',
       'unemployment_rate_1995', 'unemployment_rate_1996',
       'entrepreneurs_per_1000', 'crimes_1995', 'crimes_1996'],
      dtype='object')

In [23]:
client["district_id"].isin(district["district_id"]).all()

np.True_

In [24]:
client["district_id"].value_counts().head(10)

district_id
1     663
74    180
70    169
54    155
64    109
72    104
68     86
46     76
52     73
5      71
Name: count, dtype: int64

In [25]:
client_district = client.merge(
    district[
        [
            "district_id",
            "district_name",
            "region",
            "population",
            "average_salary",
            "unemployment_rate_1995",
            "unemployment_rate_1996"
        ]
    ],
    on="district_id",
    how="left"
)

client_district.head()

,client_id,birth_number,district_id,district_name,region,population,average_salary,unemployment_rate_1995,unemployment_rate_1996
0,1,706213,18,Pisek,south Bohemia,70699,8968,2.83,3.35
1,2,450204,1,Hl.m. Praha,Prague,1204953,12541,0.29,0.43
2,3,406009,1,Hl.m. Praha,Prague,1204953,12541,0.29,0.43
3,4,561201,5,Kolin,central Bohemia,95616,9307,3.85,4.43
4,5,605703,5,Kolin,central Bohemia,95616,9307,3.85,4.43

In [26]:
client_district.shape

(5369, 9)

In [27]:
client_district.shape[0] == client.shape[0]

True

In [28]:
client_district["client_id"].nunique() == client["client_id"].nunique()

True

In [29]:
disp = pd.read_csv(
    "../data/raw/disp.asc",
    sep=";"
)

disp.head()

   disp_id  client_id  account_id       type
0        1          1           1      OWNER
1        2          2           2      OWNER
2        3          3           2  DISPONENT
3        4          4           3      OWNER
4        5          5           3  DISPONENT

In [30]:
disp.shape

(5369, 4)

In [31]:
disp.dtypes

disp_id        int64
client_id      int64
account_id     int64
type          object
dtype: object

In [32]:
disp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5369 entries, 0 to 5368
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   disp_id     5369 non-null   int64
 1   client_id   5369 non-null   int64
 2   account_id  5369 non-null   int64
 3   type        5369 non-null   object
dtypes: int64(3), object(1)
memory usage: 167.9+ KB

In [33]:
disp["disp_id"].nunique()

5369

In [34]:
disp["disp_id"].duplicated().sum()

np.int64(0)

In [35]:
disp["type"].value_counts()

type
OWNER        4500
DISPONENT     869
Name: count, dtype: int64

In [36]:
disp["account_id"].nunique()

4500

In [37]:
disp.groupby("account_id")["client_id"].nunique().gt(1).sum()

np.int64(869)

In [38]:
owner_counts = disp[disp["type"] == "OWNER"].groupby("account_id")["client_id"].nunique()

owner_counts.value_counts()

client_id
1    4500
Name: count, dtype: int64

In [39]:
accounts_per_client = disp.groupby("client_id")["account_id"].nunique()

accounts_per_client.value_counts().sort_index()

account_id
1    5369
Name: count, dtype: int64

In [40]:
owner_counts.value_counts()

client_id
1    4500
Name: count, dtype: int64

In [41]:
account = pd.read_csv(
    "../data/raw/account.asc",
    sep=";"
)

account.head()

   account_id  district_id         frequency    date
0         576           55  POPLATEK MESICNE  930101
1        3818           74  POPLATEK MESICNE  930101
2         704           55  POPLATEK MESICNE  930101
3        2378           16  POPLATEK MESICNE  930101
4        2632           24  POPLATEK MESICNE  930102

In [42]:
account.shape

(4500, 4)

In [43]:
account.dtypes

account_id      int64
district_id     int64
frequency      object
date            int64
dtype: object

In [44]:
account.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   account_id   4500 non-null   int64
 1   district_id  4500 non-null   int64
 2   frequency    4500 non-null   object
 3   date         4500 non-null   int64
dtypes: int64(3), object(1)
memory usage: 140.8+ KB

In [45]:
account["account_id"].nunique()

4500

In [46]:
account["account_id"].duplicated().sum()

np.int64(0)

In [47]:
disp["account_id"].isin(account["account_id"]).all()

np.True_

In [48]:
account["frequency"].value_counts()

frequency
POPLATEK MESICNE      4167
POPLATEK TYDNE         240
POPLATEK PO OBRATU      93
Name: count, dtype: int64

In [49]:
account["date"].head(20).tolist()

[930101,
 930101,
 930101,
 930101,
 930102,
 930102,
 930103,
 930103,
 930103,
 930103,
 930103,
 930104,
 930104,
 930104,
 930104,
 930105,
 930105,
 930106,
 930106,
 930107]

In [50]:
account["date"].nunique()

1535

In [51]:
account["date"].min()

np.int64(930101)

In [52]:
account["date"].max()

np.int64(971229)

In [53]:
account["account_open_date"] = pd.to_datetime(
    account["date"].astype(str),
    format="%y%m%d"
)

account[["date", "account_open_date"]].head()

     date account_open_date
0  930101        1993-01-01
1  930101        1993-01-01
2  930101        1993-01-01
3  930101        1993-01-01
4  930102        1993-01-02

In [54]:
account["account_open_date"].dtype

dtype('<M8[ns]')

In [55]:
account["account_open_date"].dt.year.value_counts().sort_index()

account_open_date
1993    1139
1994     439
1995     661
1996    1363
1997     898
Name: count, dtype: int64

In [56]:
account["account_open_date"].dt.year.value_counts(normalize=True).sort_index() * 100

account_open_date
1993    25.311111
1994     9.755556
1995    14.688889
1996    30.288889
1997    19.955556
Name: proportion, dtype: float64

In [57]:
trans = pd.read_csv(
    "../data/raw/trans.asc",
    sep=";"
)

trans.head()

C:\Users\alexa\AppData\Local\Temp\ipykernel_20224\4161590805.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  trans = pd.read_csv(

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
0,695247,2378,930101,PRIJEM,VKLAD,700.0,700.0,NaN,NaN,NaN
1,171812,576,930101,PRIJEM,VKLAD,900.0,900.0,NaN,NaN,NaN
2,207264,704,930101,PRIJEM,VKLAD,1000.0,1000.0,NaN,NaN,NaN
3,1117247,3818,930101,PRIJEM,VKLAD,600.0,600.0,NaN,NaN,NaN
4,579373,1972,930102,PRIJEM,VKLAD,400.0,400.0,NaN,NaN,NaN

In [58]:
trans.shape

(1056320, 10)

In [59]:
trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056320 entries, 0 to 1056319
Data columns (total 10 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   trans_id    1056320 non-null  int64
 1   account_id  1056320 non-null  int64
 2   date        1056320 non-null  int64
 3   type        1056320 non-null  object
 4   operation   873206 non-null   object
 5   amount      1056320 non-null  float64
 6   balance     1056320 non-null  float64
 7   k_symbol    574439 non-null   object
 8   bank        273508 non-null   object
 9   account     295389 non-null   float64
dtypes: float64(3), int64(3), object(4)
memory usage: 80.6+ MB

In [60]:
trans.isna().sum()

trans_id           0
account_id         0
date               0
type               0
operation     183114
amount             0
balance            0
k_symbol      481881
bank          782812
account       760931
dtype: int64

In [61]:
trans.isna().mean() * 100

trans_id       0.000000
account_id     0.000000
date           0.000000
type           0.000000
operation     17.335088
amount         0.000000
balance        0.000000
k_symbol      45.618847
bank          74.107467
account       72.036031
dtype: float64

In [62]:
trans["type"].value_counts()

type
VYDAJ     634571
PRIJEM    405083
VYBER      16666
Name: count, dtype: int64

In [63]:
trans["operation"].value_counts(dropna=False)

operation
VYBER             434918
PREVOD NA UCET    208283
NaN               183114
VKLAD             156743
PREVOD Z UCTU      65226
VYBER KARTOU        8036
Name: count, dtype: int64

In [64]:
trans["k_symbol"].value_counts(dropna=False)

k_symbol
NaN            481881
UROK           183114
SLUZBY         155832
SIPO           118065
                53433
DUCHOD          30338
POJISTNE        18500
UVER            13580
SANKC. UROK      1577
Name: count, dtype: int64

In [65]:
trans["type"].value_counts(normalize=True) * 100

type
VYDAJ     60.073747
PRIJEM    38.348512
VYBER      1.577742
Name: proportion, dtype: float64

In [66]:
trans["date"].min()

np.int64(930101)

In [67]:
trans["date"].max()

np.int64(981231)

In [68]:
trans["date"].nunique()

2191

In [69]:
trans["transaction_date"] = pd.to_datetime(
    trans["date"].astype(str),
    format="%y%m%d"
)

trans[["date", "transaction_date"]].head()

     date transaction_date
0  930101       1993-01-01
1  930101       1993-01-01
2  930101       1993-01-01
3  930101       1993-01-01
4  930102       1993-01-02

In [70]:
trans["amount"].describe()

count    1.056320e+06
mean     5.924146e+03
std      9.522735e+03
min      0.000000e+00
25%      1.359000e+02
50%      2.100000e+03
75%      6.800000e+03
max      8.740000e+04
Name: amount, dtype: float64

In [71]:
trans["balance"].describe()

count    1.056320e+06
mean     3.851833e+04
std      2.211787e+04
min     -4.112570e+04
25%      2.240250e+04
50%      3.314340e+04
75%      4.960362e+04
max      2.096370e+05
Name: balance, dtype: float64

In [72]:
trans["amount"].isna().sum()

np.int64(0)

In [73]:
(trans["amount"] == 0).sum()

np.int64(14)

In [74]:
trans.loc[trans["amount"] == 0, ["type", "operation", "k_symbol"]].value_counts(dropna=False)

type    operation  k_symbol
VYDAJ   VYBER      SANKC. UROK    10
PRIJEM  NaN        UROK            4
Name: count, dtype: int64

In [75]:
trans["trans_id"].nunique()

1056320

In [76]:
trans["trans_id"].duplicated().sum()

np.int64(0)

In [77]:
trans["account_id"].nunique()

4500

In [78]:
trans["account_id"].isin(account["account_id"]).all()

np.True_

In [79]:
trans["account_id"].isin(account["account_id"]).sum()

np.int64(1056320)

In [80]:
loan = pd.read_csv(
    "../data/raw/loan.asc",
    sep=";"
)

loan.head()

   loan_id  account_id    date  amount  duration  payments status
0     5314        1787  930705   96396        12    8033.0      B
1     5316        1801  930711  165960        36    4610.0      A
2     6863        9188  930728  127080        60    2118.0      A
3     5325        1843  930803  105804        36    2939.0      A
4     7240       11013  930906  274740        60    4579.0      A

In [81]:
loan.shape

(682, 7)

In [82]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   loan_id     682 non-null    int64
 1   account_id  682 non-null    int64
 2   date        682 non-null    int64
 3   amount      682 non-null    int64
 4   duration    682 non-null    int64
 5   payments    682 non-null    float64
 6   status      682 non-null    object
dtypes: float64(1), int64(5), object(1)
memory usage: 37.4+ KB

In [83]:
loan["loan_id"].nunique()

682

In [84]:
loan["loan_id"].duplicated().sum()

np.int64(0)

In [85]:
loan["account_id"].isin(account["account_id"]).all()

np.True_

In [86]:
loan["status"].value_counts()

status
C    403
A    203
D     45
B     31
Name: count, dtype: int64

In [87]:
loan["status"].value_counts(normalize=True) * 100

status
C    59.090909
A    29.765396
D     6.598240
B     4.545455
Name: proportion, dtype: float64

In [90]:
loan["loan_date"] = pd.to_datetime(
    loan["date"].astype(str),
    format="%y%m%d"
)

loan[["date", "loan_date"]].head()

     date  loan_date
0  930705 1993-07-05
1  930711 1993-07-11
2  930728 1993-07-28
3  930803 1993-08-03
4  930906 1993-09-06

In [91]:
loan["loan_date"].min(), loan["loan_date"].max()

(Timestamp('1993-07-05 00:00:00'), Timestamp('1998-12-08 00:00:00'))

In [92]:
loan[["amount", "duration", "payments"]].describe()

              amount    duration     payments
count     682.000000  682.000000   682.000000
mean   151410.175953   36.492669  4190.664223
std    113372.406310   17.075219  2215.830344
min      4980.000000   12.000000   304.000000
25%     66732.000000   24.000000  2477.000000
50%    116928.000000   36.000000  3934.000000
75%    210654.000000   48.000000  5813.500000
max    590820.000000   60.000000  9910.000000

In [93]:
loan["duration"].value_counts().sort_index()

duration
12    131
24    138
36    130
48    138
60    145
Name: count, dtype: int64

In [94]:
loan[["amount", "duration", "payments"]].isna().sum()

amount      0
duration    0
payments    0
dtype: int64

In [95]:
loan["calculated_total_payments"] = (
    loan["payments"] * loan["duration"]
)

loan[
    ["amount", "duration", "payments", "calculated_total_payments"]
].head(10)

   amount  duration  payments  calculated_total_payments
0   96396        12    8033.0                    96396.0
1  165960        36    4610.0                   165960.0
2  127080        60    2118.0                   127080.0
3  105804        36    2939.0                   105804.0
4  274740        60    4579.0                   274740.0
5   87840        24    3660.0                    87840.0
6   52788        12    4399.0                    52788.0
7  174744        24    7281.0                   174744.0
8  154416        48    3217.0                   154416.0
9  117024        24    4876.0                   117024.0

In [96]:
loan["calculated_total_payments"].describe()

count       682.000000
mean     151410.175953
std      113372.406310
min        4980.000000
25%       66732.000000
50%      116928.000000
75%      210654.000000
max      590820.000000
Name: calculated_total_payments, dtype: float64

In [97]:
loan.drop(columns="calculated_total_payments", inplace=True)

In [98]:
loan.columns

Index(['loan_id', 'account_id', 'date', 'amount', 'duration', 'payments',
       'status', 'loan_date'],
      dtype='object')

In [99]:
card = pd.read_csv(
    "../data/raw/card.asc",
    sep=";"
)

card.head()

   card_id  disp_id     type           issued
0     1005     9285  classic  931107 00:00:00
1      104      588  classic  940119 00:00:00
2      747     4915  classic  940205 00:00:00
3       70      439  classic  940208 00:00:00
4      577     3687  classic  940215 00:00:00

In [100]:
card.shape
card.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   card_id  892 non-null    int64
 1   disp_id  892 non-null    int64
 2   type     892 non-null    object
 3   issued   892 non-null    object
dtypes: int64(2), object(2)
memory usage: 28.0+ KB

In [101]:
card["card_id"].nunique()

892

In [102]:
card["card_id"].duplicated().sum()

np.int64(0)

In [103]:
card["type"].value_counts()

type
classic    659
junior     145
gold        88
Name: count, dtype: int64

In [104]:
card["disp_id"].isin(disp["disp_id"]).all()

np.True_

In [105]:
card["card_issue_date"] = pd.to_datetime(
    card["issued"],
    format="%y%m%d %H:%M:%S"
)

In [106]:
card[["issued", "card_issue_date"]].head()

            issued card_issue_date
0  931107 00:00:00      1993-11-07
1  940119 00:00:00      1994-01-19
2  940205 00:00:00      1994-02-05
3  940208 00:00:00      1994-02-08
4  940215 00:00:00      1994-02-15

In [107]:
card["card_issue_date"].min(), card["card_issue_date"].max()

(Timestamp('1993-11-07 00:00:00'), Timestamp('1998-12-29 00:00:00'))

In [108]:
order = pd.read_csv(
    "../data/raw/order.asc",
    sep=";"
)

order.head()

   order_id  account_id bank_to  account_to  amount k_symbol
0     29401           1      YZ    87144583  2452.0     SIPO
1     29402           2      ST    89597016  3372.7     UVER
2     29403           2      QR    13943797  7266.0     SIPO
3     29404           3      WX    83084338  1135.0     SIPO
4     29405           3      CD    24485939   327.0

In [109]:
order.shape
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6471 entries, 0 to 6470
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    6471 non-null   int64
 1   account_id  6471 non-null   int64
 2   bank_to     6471 non-null   object
 3   account_to  6471 non-null   int64
 4   amount      6471 non-null   float64
 5   k_symbol    6471 non-null   object
dtypes: float64(1), int64(3), object(2)
memory usage: 303.5+ KB

In [110]:
order["order_id"].nunique()

6471

In [111]:
order["order_id"].duplicated().sum()

np.int64(0)

In [112]:
order["account_id"].isin(account["account_id"]).all()

np.True_

In [113]:
order["k_symbol"].value_counts(dropna=False)

k_symbol
SIPO        3502
            1379
UVER         717
POJISTNE     532
LEASING      341
Name: count, dtype: int64